
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS
{

using System;
    using System.Collections.Generic;
    
public partial class ClientOrderDetail
{

    public int OrderID { get; set; }

    public Nullable<int> ClientID { get; set; }

    public int ProductID { get; set; }

    public Nullable<int> Quantity { get; set; }

    public string OrderState { get; set; }

    public Nullable<int> WarehouseID { get; set; }



    public virtual ClientOrder ClientOrder { get; set; }

    public virtual Warehouse Warehouse { get; set; }

}

}
