
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS
{

using System;
    using System.Collections.Generic;
    
public partial class SuggestedRefillOrder
{

    public int SuggestedOrderID { get; set; }

    public Nullable<int> WarehouseID { get; set; }

    public Nullable<int> ProductID { get; set; }



    public virtual Warehouse Warehouse { get; set; }

}

}
