
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS
{

using System;
    using System.Collections.Generic;
    
public partial class Warehouse
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Warehouse()
    {

        this.Products = new HashSet<Product>();

        this.RefillOrders = new HashSet<RefillOrder>();

        this.ClientOrderDetails = new HashSet<ClientOrderDetail>();

        this.SuggestedRefillOrders = new HashSet<SuggestedRefillOrder>();

    }


    public int WarehouseID { get; set; }

    public string Address { get; set; }

    public Nullable<int> NumberOfRows { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Products { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RefillOrder> RefillOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ClientOrderDetail> ClientOrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SuggestedRefillOrder> SuggestedRefillOrders { get; set; }

}

}
